---
title: tidyTuesday meets the Economics of Majors
author: RWW
date: '2018-10-17'
slug: tidytuesday-meets-the-economics-of-majors
categories: []
tags: [tidyTuesday]
header:
  caption: ''
  image: ''
---

This week's tidyTuesday focuses on degrees and majors and their deployment in the labor market.  The original data came from 538.  A description of sources and measures.  The tidyTesday writeup is [here](https://github.com/fivethirtyeight/data/tree/master/college-majors).

```{r, message=FALSE}
library(tidyverse)
options(scipen=6)
library(extrafont)
font_import()
Major.Employment <- read.csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2018-10-16/recent-grads.csv")
```

A scatterplot of the unemployment rate by majors is the first goal with a color scheme that reflects the proportion of females in the industry.

```{r}
my.plot <- Major.Employment %>% ggplot(aes(Unemployment_rate,Median, label=str_to_title(Major), color=ShareWomen)) +
  geom_point() +
  geom_text(check_overlap = T, vjust=-0.5, nudge_y=0.1, size=2.5) +
  theme_minimal() +
  scale_color_gradient(name="Share of Women", low="#de2d26", high = "#e9a3c9") + 
  scale_y_continuous(labels = scales::comma) +
  scale_x_continuous(labels = scales::percent) + 
  xlab("Unemployment Rate") +
  ylab("Median Income") +
  ggtitle("Median Income and Unemployment") +
  theme(text=element_text(family = "Roboto Light", size=8), title = element_text(size=12)) 
my.plot
```

```{r}
Major.Employment <- Major.Employment %>% mutate(ShareCol= College_jobs / Total)
my.plot <- Major.Employment %>% ggplot(aes(Unemployment_rate,ShareCol, label=str_to_title(Major), color=ShareWomen)) +
  geom_point(alpha=0.1) +
  geom_text(check_overlap = T, size=1.5) +
  theme_minimal() +
  scale_color_gradient(name="Share of Women", low="#de2d26", high = "#e9a3c9") + 
#  scale_y_continuous(labels = scales::comma) +
  scale_x_continuous(labels = scales::percent) + 
  xlab("Unemployment Rate") +
  ylab("College Pct.") +
  ggtitle("College Pct. Jobs and Unemployment")
my.plot
```

