---
title: 'Dog Movements: a tidyTuesday'
author: RWW
date: '2019-12-17'
slug: dog-movements-a-tidytuesday
categories:
  - tidyverse
  - tidyTuesday
tags:
  - R
  - R Markdown
  - tidyTuesday
  - tidyverse
  - Maps
header:
  caption: ''
  image: ''
  preview: yes
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Adoptable Dogs

```{r, warning=FALSE, message=FALSE}
# devtools::install_github("thebioengineer/tidytuesdayR", force=TRUE)
tuesdata51 <- tidytuesdayR::tt_load(2019, week = 51)
dog_moves <- tuesdata51$dog_moves
library(tidyverse); library(scatterpie)
library(rgeos)
library(maptools)
library(rgdal); library(usmap); library(ggthemes)
```


# The Base Map

```{r}
My.Map <- us_map(regions = "states")
Base.Plot <- ggplot() + geom_polygon(data=My.Map, aes(x=x, y=y, group=group), fill="white", color="black") + theme_map()
Base.Plot
```

A fifty state map to plot this information on.

```{r}
New.Dat <- left_join(My.Map, dog_moves, by= c("full" = "location"))
ggplot() + geom_polygon(data=New.Dat, aes(x=x, y=y, group=group, fill=total), color="black") + scale_fill_viridis_c() + labs(title = "Dogs Available for Adoption")
```

That's a start.  Now for the scatterpie.  After a bit of work, I needed to translate the coordinates from most common maps.  So I started with a ggmap for easier to work with coordinates.

```{r F2, warning=FALSE, message=FALSE}
library(sf); library(ggmap)
states <- maps::map("state", plot = FALSE, fill=TRUE)
states <- st_as_sf(states)
statesC <- cbind(states, st_coordinates(st_centroid(states)))
dog_moves <-dog_moves %>% mutate(ID = tolower(location))
statesC <- left_join(statesC, dog_moves)
statesC %>% filter(!is.na(imported) & !is.na(exported) & !is.na(total)) %>% select(X, Y, exported, imported, total) %>% data.frame() -> ShortCD
My.SM <- get_map(c(-124.6813, 25.12993, -67.00742, 49.00508), source="osm")
ggmap(My.SM) + geom_scatterpie(data=ShortCD, aes(x=X, y=Y, r=total/3000), cols=c("exported","imported")) + labs(fill="Dog Movements") + theme_map()
```

